env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2021
rules: 
  semi: off
  line-break-style: off
  linebreak-style: off
  no-use-before-define: off
  import/prefer-default-export: off
  comma-dangle: off
  no-console: off
  import/no-extraneous-dependencies: off

