service: serverless-tut-7

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1

functions:
  hello:
    handler: src/function.handler
    events:
      - http:
          path: hello
          method: GET
