@host = xyz

####
# getAll - local
GET {{host}}/dev/products


####
# create - local
POST {{host}}/dev/products
Content-Type: application/json

{
    "name": "sneakersdd",
    "description": "sneaker shoes description"
}

####
# getById - local
GET {{host}}/dev/products/f4014a2c-20fb-428c-a1d6-909c3e063aa3


####
# update - local
PUT {{host}}/dev/products/f4014a2c-20fb-428c-a1d6-909c3e063aa3
Content-Type: application/json

{
    "name": "sneakers updated",
    "description": "sneaker shoes new description"
}

####
# delete - local
DELETE  {{host}}/dev/products/id